version: '3.8'

services:
  go-app:
    image: golang:1.22.3
    container_name: SomersaultCloud-G
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=mini_gpt
      - RABBITMQ_URL=${RABBITMQ_URL:-rabbitmq-g}
      - REDIS_URL=${REDIS_URL:-redis:6379}
    depends_on:
      - mysql
      - rabbitmq
      - redis
    ports:
      - "3000:3000"    # 映射端口
    command: ["go", "run", "./cmd"]  # 你可以根据需求调整这部分

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-g
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mini_gpt
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/SomersaultCloud.sql

  db-init:
    image: mysql:8.0
    depends_on:
      - mysql
    volumes:
      - ./SomersaultCloud.sql:/docker-entrypoint-initdb.d/SomersaultCloud.sql
    entrypoint: /bin/sh -c "until mysqladmin ping -h mysql --silent; do echo waiting for mysql; sleep 2; done && exit 0"
