// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: chatHistory.proto

package __proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordId        int32           `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	ChatAsks        *ChatAsk        `protobuf:"bytes,2,opt,name=chat_asks,json=chatAsks,proto3" json:"chat_asks,omitempty"`
	ChatGenerations *ChatGeneration `protobuf:"bytes,3,opt,name=chat_generations,json=chatGenerations,proto3" json:"chat_generations,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatHistory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_chatHistory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_chatHistory_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetRecordId() int32 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *Record) GetChatAsks() *ChatAsk {
	if x != nil {
		return x.ChatAsks
	}
	return nil
}

func (x *Record) GetChatGenerations() *ChatGeneration {
	if x != nil {
		return x.ChatGenerations
	}
	return nil
}

type ChatAsk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId  int32  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BotId   int32  `protobuf:"varint,3,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Time    int64  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *ChatAsk) Reset() {
	*x = ChatAsk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatHistory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAsk) ProtoMessage() {}

func (x *ChatAsk) ProtoReflect() protoreflect.Message {
	mi := &file_chatHistory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAsk.ProtoReflect.Descriptor instead.
func (*ChatAsk) Descriptor() ([]byte, []int) {
	return file_chatHistory_proto_rawDescGZIP(), []int{1}
}

func (x *ChatAsk) GetChatId() int32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ChatAsk) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatAsk) GetBotId() int32 {
	if x != nil {
		return x.BotId
	}
	return 0
}

func (x *ChatAsk) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ChatGeneration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Time    int64  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *ChatGeneration) Reset() {
	*x = ChatGeneration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatHistory_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatGeneration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatGeneration) ProtoMessage() {}

func (x *ChatGeneration) ProtoReflect() protoreflect.Message {
	mi := &file_chatHistory_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatGeneration.ProtoReflect.Descriptor instead.
func (*ChatGeneration) Descriptor() ([]byte, []int) {
	return file_chatHistory_proto_rawDescGZIP(), []int{2}
}

func (x *ChatGeneration) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatGeneration) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type RecordsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *RecordsList) Reset() {
	*x = RecordsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatHistory_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordsList) ProtoMessage() {}

func (x *RecordsList) ProtoReflect() protoreflect.Message {
	mi := &file_chatHistory_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordsList.ProtoReflect.Descriptor instead.
func (*RecordsList) Descriptor() ([]byte, []int) {
	return file_chatHistory_proto_rawDescGZIP(), []int{3}
}

func (x *RecordsList) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_chatHistory_proto protoreflect.FileDescriptor

var file_chatHistory_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x68, 0x61, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x22, 0x9a, 0x01,
	0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x61, 0x73,
	0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x41, 0x73, 0x6b, 0x52, 0x08, 0x63, 0x68, 0x61,
	0x74, 0x41, 0x73, 0x6b, 0x73, 0x12, 0x43, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x63, 0x68, 0x61, 0x74, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x67, 0x0a, 0x07, 0x43, 0x68,
	0x61, 0x74, 0x41, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x42, 0x08,
	0x5a, 0x06, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chatHistory_proto_rawDescOnce sync.Once
	file_chatHistory_proto_rawDescData = file_chatHistory_proto_rawDesc
)

func file_chatHistory_proto_rawDescGZIP() []byte {
	file_chatHistory_proto_rawDescOnce.Do(func() {
		file_chatHistory_proto_rawDescData = protoimpl.X.CompressGZIP(file_chatHistory_proto_rawDescData)
	})
	return file_chatHistory_proto_rawDescData
}

var file_chatHistory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chatHistory_proto_goTypes = []any{
	(*Record)(nil),         // 0: recordpb.Record
	(*ChatAsk)(nil),        // 1: recordpb.ChatAsk
	(*ChatGeneration)(nil), // 2: recordpb.ChatGeneration
	(*RecordsList)(nil),    // 3: recordpb.RecordsList
}
var file_chatHistory_proto_depIdxs = []int32{
	1, // 0: recordpb.Record.chat_asks:type_name -> recordpb.ChatAsk
	2, // 1: recordpb.Record.chat_generations:type_name -> recordpb.ChatGeneration
	0, // 2: recordpb.RecordsList.records:type_name -> recordpb.Record
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chatHistory_proto_init() }
func file_chatHistory_proto_init() {
	if File_chatHistory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chatHistory_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatHistory_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ChatAsk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatHistory_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ChatGeneration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatHistory_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RecordsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chatHistory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatHistory_proto_goTypes,
		DependencyIndexes: file_chatHistory_proto_depIdxs,
		MessageInfos:      file_chatHistory_proto_msgTypes,
	}.Build()
	File_chatHistory_proto = out.File
	file_chatHistory_proto_rawDesc = nil
	file_chatHistory_proto_goTypes = nil
	file_chatHistory_proto_depIdxs = nil
}
