// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"SomersaultCloud/app/somersaultcloud-exporter/api/grpc"
	"SomersaultCloud/app/somersaultcloud-exporter/bootstrap"
	"SomersaultCloud/app/somersaultcloud-exporter/monitor"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp init application.
func InitializeApp() (*bootstrap.ExportApplication, error) {
	exporterEnv := bootstrap.NewEnv()
	grpcConn := grpc.NewGrpcConn(exporterEnv)
	serviceDiscovery := bootstrap.NewServiceDiscovery(exporterEnv)
	domainMonitor := monitor.NewMonitor(grpcConn, exporterEnv, serviceDiscovery)
	exportApplication := &bootstrap.ExportApplication{
		Env:     exporterEnv,
		Monitor: domainMonitor,
	}
	return exportApplication, nil
}

// wire.go:

var appSet = wire.NewSet(bootstrap.NewEnv, bootstrap.NewServiceDiscovery, grpc.NewGrpcConn, monitor.NewMonitor, wire.Struct(new(bootstrap.ExportApplication), "*"))
