// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"SomersaultCloud/api/controller"
	"SomersaultCloud/bootstrap"
	"SomersaultCloud/cron"
	"SomersaultCloud/internal/tokenutil"
	"SomersaultCloud/repository"
	"SomersaultCloud/task"
	"SomersaultCloud/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp init application.
func InitializeApp() (*bootstrap.Application, error) {
	env := bootstrap.NewEnv()
	databases := bootstrap.NewDatabases(env)
	poolsFactory := bootstrap.NewPoolFactory()
	channels := bootstrap.NewChannel()
	chatRepository := repository.NewChatRepository(databases)
	botRepository := repository.NewBotRepository(databases)
	askTask := task.NewAskChatTask(botRepository, chatRepository, env, channels)
	chatUseCase := usecase.NewChatUseCase(env, chatRepository, botRepository, askTask)
	chatController := controller.NewChatController(chatUseCase)
	controllers := bootstrap.NewControllers(chatController)
	executor := cron.NewExecutor()
	application := &bootstrap.Application{
		Env:          env,
		Databases:    databases,
		PoolsFactory: poolsFactory,
		Channels:     channels,
		Controllers:  controllers,
		Executor:     executor,
	}
	return application, nil
}

// wire.go:

var appSet = wire.NewSet(bootstrap.NewEnv, bootstrap.NewDatabases, bootstrap.NewRedisDatabase, bootstrap.NewMysqlDatabase, bootstrap.NewMongoDatabase, bootstrap.NewPoolFactory, bootstrap.NewChannel, bootstrap.NewControllers, repository.NewGenerationRepository, repository.NewChatRepository, repository.NewBotRepository, cron.NewExecutor, cron.NewAsyncService, usecase.NewChatUseCase, task.NewAskChatTask, controller.NewChatController, tokenutil.NewTokenUtil, wire.Struct(new(bootstrap.Application), "*"))
