// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"SomersaultCloud/app/somersaultcloud-ipconfig/bootstrap"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp init application.
func InitializeApp() (*bootstrap.IpConfigApplication, error) {
	ipConfigEnv := bootstrap.NewEnv()
	dataHandler := bootstrap.NewDataHandler(ipConfigEnv)
	dispatcher := bootstrap.NewDispatcher(ipConfigEnv)
	api := bootstrap.NewApi(dataHandler, dispatcher)
	serviceDiscovery := bootstrap.NewServiceDiscovery(ipConfigEnv)
	ipConfigApplication := &bootstrap.IpConfigApplication{
		Env:         ipConfigEnv,
		Api:         api,
		Discovery:   serviceDiscovery,
		DataHandler: dataHandler,
		Dispatcher:  dispatcher,
	}
	return ipConfigApplication, nil
}

// wire.go:

var appSet = wire.NewSet(bootstrap.NewEnv, bootstrap.NewServiceDiscovery, bootstrap.NewDispatcher, bootstrap.NewDataHandler, bootstrap.NewApi, wire.Struct(new(bootstrap.IpConfigApplication), "*"))
