// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"SomersaultCloud/app/somersaultcloud-ipconfig/bootstrap"
	"SomersaultCloud/app/somersaultcloud-ipconfig/dispatcher"
	"SomersaultCloud/app/somersaultcloud-ipconfig/source"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp init application.
func InitializeApp() (*bootstrap.IpConfigApplication, error) {
	ipConfigEnv := bootstrap.NewEnv()
	domainDispatcher := dispatcher.NewDispatcher(ipConfigEnv)
	api := bootstrap.NewApi(domainDispatcher)
	serviceDiscovery := bootstrap.NewServiceDiscovery(ipConfigEnv)
	dataHandler := source.NewDataHandler(ipConfigEnv, serviceDiscovery)
	ipConfigApplication := &bootstrap.IpConfigApplication{
		Env:         ipConfigEnv,
		Api:         api,
		Discovery:   serviceDiscovery,
		DataHandler: dataHandler,
		Dispatcher:  domainDispatcher,
	}
	return ipConfigApplication, nil
}

// wire.go:

var appSet = wire.NewSet(bootstrap.NewEnv, bootstrap.NewServiceDiscovery, bootstrap.NewApi, dispatcher.NewDispatcher, source.NewDataHandler, wire.Struct(new(bootstrap.IpConfigApplication), "*"))
